source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.10"
gem "jekyll-optional-front-matter"
gem "jekyll-titles-from-headings"
gem "jekyll-relative-links"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
